baseURL = "/"
title = "Tinkle"

enableRobotsTXT = true

# Will give values to .Lastmod etc.
enableGitInfo = false

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

# Language configuration

[languages]
[languages.en.params]
title = "Tinkle"
description = "A macOS app that appends a visual effect at the focused window changes."
languageName ="English"
# Weight used for sorting.
weight = 1

# Everything below this are Site Params

[params]

# First one is picked as the Twitter card image if not set on page.
images = ["https://tinkle.pqrs.org/images/logo.png"]

offlineSearch = true
offlineSearchSummaryLength = 200
offlineSearchMaxResults = 25

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
# sidebar_search_disable = true
sidebar_menu_foldable = true
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = false
# Set to true to disable the About link in the site footer
footer_about_disable = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = false

[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
